version: "3.9"

services:
  app:
    build: .
    container_name: dinner-awards-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
      - minio

  mongo:
    image: mongo:6
    container_name: dinner-awards-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  minio:
    image: minio/minio:latest
    container_name: dinner-awards-minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  mongo_data:
  minio_data:
